Fix: Remove invalid jsx prop
The error `src/components/Dashboard.tsx(810,14): error TS2322: Type '{ children: string; jsx: true; }' is not assignable to type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'. Property 'jsx' does not exist on type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'` indicates an invalid `jsx` prop is being used. This commit removes the invalid prop.